AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  workout-app

  Sample SAM Template for workout-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - arm64

  WorkoutTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "WorkoutTable"
      AttributeDefinitions:
        - AttributeName: "username"
          AttributeType: "S"
        - AttributeName: "date#exercise"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "username"
          KeyType: "HASH" # Partition key
        - AttributeName: "date#exercise"
          KeyType: "RANGE" # Sort key
      BillingMode: PAY_PER_REQUEST
